version: '3.8'

services:
  web:
    build: .
    restart: always
    ports:
      - "5006:5006"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - FLASK_ENV=production
      # Overriding DATABASE_URL to point to local db service in docker-compose
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - DB_SSLMODE=disable
    networks:
      - portal_network

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - portal_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  portal_network:

volumes:
  postgres_data:
